config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "secure"

  get "/home", to: "pages#home"
  get "/about", to: "pages#about"

  resources :entries

  root "entries#index"

  # Api definition
  namespace :api do
    namespace :v1 do
      post :auth, to: "auth#create"
      resources :entries
    end

    namespace :v2, defaults: { format: :json } do
      resources :users
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  validates :name, :username, :password, presence: true
  validate :url_must_be_valid

  encrypts :username, deterministic: true
  encrypts :password

  scope :search_name, ->(name) {
    where("entries.name ILIKE ?", "%#{name}%") if name.present?
  }

  def self.search(name)
    search_name(name).order(:name)
  end

  private

  def url_must_be_valid
    unless url.include?("http" || "https")
      errors.add(:url, "must be valid")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries, dependent: :destroy

  validates :email, uniqueness: true
end

app/controllers/api/v1/api_base_controller.rb
class Api::V1::ApiBaseController < ApplicationController
  attr_reader :current_user

  skip_before_action :verify_authenticity_token

  before_action :authenticate_token
  before_action :set_json_format

  private

  def authenticate_token
    payload = JsonWebToken.decode(auth_token)

    if payload[:error]
      render json: { errors: [ payload[:error] ] }, status: :unauthorized
    else
      @current_user = User.find(payload["sub"])
    end
  end

  def auth_token
    @auth_token ||= request.headers["Authorization"]&.split(" ")&.last
  end

  def set_json_format
    request.format = :json
  end
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < Api::V1::ApiBaseController
  skip_before_action :authenticate_token

  def create
    user = User.find_by(email: params[:email])
    if user&.valid_password?(params[:password])
      render json: { token: JsonWebToken.encode(sub: user.id) }, status: :ok
    else
      render json: { errors: [ "Invalid email or password" ] }, status: :unauthorized
    end
  end
end

app/controllers/api/v1/entries_controller.rb
class Api::V1::EntriesController < Api::V1::ApiBaseController
  def index
    render json: current_user.entries
  end
end

app/controllers/api/v2/api_base_controller.rb
class Api::V2::ApiBaseController < ApplicationController
  attr_reader :current_user

  skip_before_action :verify_authenticity_token
end

app/controllers/api/v2/users_controller.rb
class Api::V2::UsersController < Api::V2::ApiBaseController
  def show
    render json: {}, status: :ok
  end

  private

  def user_params
    params.permit(:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, only: %i[show edit update destroy]

  def index
    @entries = current_user.entries.search(params[:name])
    @main_entry = @entries.first

    return unless params[:name].present?

    if @entries.length == 1
      render turbo_stream: [
        turbo_stream.update("main-dashboard", partial: "entries/main", locals: { entry: @entries.first }),
        turbo_stream.update("entries-list", partial: "entries/entry", locals: { entry: @entries.first })
      ]
    end
  end

  def new
    @entry = Entry.new
  end


  def edit
  end

  def update
    if @entry.update(entry_params)
      flash.now[:notice] = "#{@entry.name} has been updated.".html_safe
      respond_to do |format|
        format.html { redirect_to @entry }
        format.turbo_stream { }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
  end

  def create
    @entry = current_user.entries.new(entry_params)

    if @entry.save
      flash.now[:notice] = "<strong>#{@entry.name}</strong> Entry has been saved!".html_safe
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream { }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @entry.destroy
    flash.now[:notice] = "#{@entry.name} has been deleted."
    respond_to do |format|
      format.html { redirect_to root_path }
      format.turbo_stream { }
    end
  end

  private

  def entry_params
    params.expect(entry: [ :name, :url, :username, :password ])
  end

  def set_entry
    @entry = current_user.entries.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo(size = "h2")
    link_to(root_path, class: "navbar-brand fw-bold logo #{size}") do
      "<i class=\"bi bi-safe-fill me-2\"></i> SafePass".html_safe
    end
  end

  def account_page?
    current_page?(edit_user_registration_path)
  end

  def format_time(time)
    time.strftime("%m/%d/%Y, %I:%M %p")
  end

  def render_flash_stream
    turbo_stream.update("flash", partial: "shared/flash")
  end
end


# <%= link_to root_path, class: "navbar-brand fw-bold"  do %>
#   <i class="bi bi-safe-fill me-2"></i>
#   SafePass
# <% end %>

app/helpers/flash_helper.rb
module FlashHelper
 def flash_class(type)
   puts type
   case type
   when "notice" then "success"
   when "alert" then "danger"
   end
 end
end

app/views/entries/_entry.html.erb
<%= link_to entry_path(entry), class: "nav-link", data: { turbo_frame: 'main-dashboard' }, id: dom_id(entry) do %>
  <%= render(layout: 'entries/entry_name', locals: { entry: entry}) do %>
    <%= entry.name %>
  <% end %>
<% end %>

app/views/entries/_entry_name.html.erb
<div class="d-flex align-items-center">
  <div class="entry-favicon">
    <%= image_tag("https://www.google.com/s2/favicons?domain=#{entry.url}&sz=32", alt: entry.name) %>
  </div>

  <%= yield %>
</div>

app/views/entries/_main.html.erb
<div class="d-flex flex-column justify-content-between h-100">
  <div>
    <%= render(layout: 'entries/entry_name', locals: { entry: entry}) do %>
      <div
        id="entry-name"
        class="d-flex align-items-center justify-content-between flex-grow-1"
      >
        <%= turbo_frame_tag(:entry_name, class: 'w-100') do %>
          <h1 class="mb-0"><%= entry.name %></h1>
        <% end %>

        <div class="dropdown">
          <button
            class="btn btn-outline-light border-0 text-dark me-3"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="bi bi-three-dots-vertical"></i>
          </button>

          <ul class="dropdown-menu">
            <li>
              <%= link_to(edit_entry_path(entry, input: :entry_name), data: { turbo_frame:  :entry_name}, class: "dropdown-item") do %>
                <i class="bi bi-pencil-square"></i>
                Edit Name
              <% end %>
            </li>

            <li>
              <%= link_to entry_path(entry), data: { turbo_method: :delete }, class: 'dropdown-item text-danger'  do %>
                <i class="bi bi-trash3-fill"></i>
                Delete Entry
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="mt-5">
      <ul class="list-group">
        <li id="entry-username" class="list-group-item">
          <%= turbo_frame_tag(:entry_username) do %>
            <div class="d-flex justify-content-between align-items-center">
              <div class="form-floating w-100">
                <%= text_field_tag(:username, entry.username, readonly: true, class: "form-control-plaintext", placeholder: "email") %>
                <%= label_tag(:username, "Username", class: 'fw-bold text-dark') %>
              </div>

              <div class="actions d-flex">
                <button
                  class="btn btn-outline-primary border-0"
                  data-controller="clipboard"
                  data-action="click->clipboard#copy"
                  data-clipboard-content-param="<%= entry.username %>"
                >
                  <i class="bi bi-clipboard-plus"></i>
                </button>

                <%= link_to(edit_entry_path(entry, input: :entry_username), class: 'btn btn-outline-light border-0 text-dark') do %>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </li>

        <li
          id="entry-password"
          class="list-group-item"
          data-controller="toggle-password"
        >
          <%= turbo_frame_tag(:entry_password) do %>
            <div class="d-flex justify-content-between align-items-center">
              <div class="form-floating w-100">
                <%= text_field_tag(:password, entry.password, readonly: true, class: "form-control-plaintext", type: :password, placeholder: "password", data: {toggle_password_target: 'input'}) %>
                <%= label_tag(:password, "Password", class: 'fw-bold text-dark') %>
              </div>

              <div class="actions d-flex">
                <button
                  class="btn btn-outline-primary border-0"
                  data-action="toggle-password#toggle"
                >
                  <i class="bi bi-eye"></i>
                </button>

                <button
                  class="btn btn-outline-primary border-0"
                  data-controller="clipboard"
                  data-action="click->clipboard#copy"
                  data-clipboard-content-param="<%= entry.password %>"
                >
                  <i class="bi bi-clipboard-plus"></i>
                </button>

                <%= link_to(edit_entry_path(entry, input: :entry_password), class: 'btn btn-outline-light border-0 text-dark') do %>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </li>
      </ul>

      <div id="entry-url" class="mt-4">
        <%= turbo_frame_tag(:entry_url) do %>
          <div class="d-flex justify-content-between align-items-center">
            <div class="flex-grow-1 ms-4 ps-1">
              <div class="fw-bold">
                URL
              </div>

              <%= link_to(entry.url, target: :_blank, rel: "noopener noreferrer") do %>
                <%= entry.url %>
                <i class="bi bi-box-arrow-up-right ms-1"></i>
              <% end %>
            </div>

            <div class="actions">
              <%= link_to(edit_entry_path(entry, input: :entry_url), class: 'btn btn-outline-light border-0 text-dark me-3') do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="text-center">
    <div>Modified at: <%= format_time(entry.updated_at) %></div>
    <div>Created at: <%= format_time(entry.created_at) %></div>
  </div>
</div>

app/views/entries/create.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.append('entries-list', @entry) %>
<%= turbo_stream.update('main-dashboard') do  %>
  <%= render(partial: 'entries/main', locals: {entry: @entry}) %>
<% end %>

app/views/entries/destroy.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.remove(@entry) %>
<%= turbo_stream.update('main-dashboard') do  %>
  <% if current_user.entries.any? %>
      <%= render(partial: 'entries/main', locals: { entry: @current_user.entries.order(:name).first }) %>
  <% else %>
      <%= render(html: content_tag(:h1, 'No Entries', class: 'h-100 d-flex align-items-center justify-content-center')) %>
  <% end %>
<% end %>

app/views/entries/edit.html.erb
<%= turbo_frame_tag(params[:input]) do |input| %>
  <%= form_with(model: @entry, class: 'd-flex position-relative')  do |form| %>
    <div class="form-floating edit-name">
      <%= form.text_field :name, placeholder: 'Name', class: "form-control" %>
      <%= form.label :name, class: 'fw-bold text-dark' %>
    </div>

    <div class="form-floating edit-url">
      <%= form.text_field :url, placeholder: 'URL', class: "form-control" %>
      <%= form.label :url, class: 'fw-bold text-dark' %>
    </div>

    <div class="form-floating edit-username">
      <%= form.text_field :username, placeholder: 'Username', class: "form-control" %>
      <%= form.label :username, class: 'fw-bold text-dark' %>
    </div>

    <div class="form-floating edit-password">
      <%= form.text_field :password, placeholder: 'Password', class: "form-control" %>
      <%= form.label :password, class: 'fw-bold text-dark' %>
    </div>

    <div class="entry-edit-actions">
      <%= form.button(class: 'btn btn-sm btn-outline-success me-2 rounded-circle') do %>
        <i class="bi bi-check-lg"></i>
      <% end %>

      <%= link_to(entry_path(@entry), class: "btn btn-sm btn-outline-danger rounded-circle") do %>
        <i class="bi bi-x-lg"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/entries/index.html.erb
<div class="row">
  <div class="entries-actions card">
    <div class="entry-search" data-controller="search">
      <%= form_with(url: entries_path, method: :get, data: { turbo_frame: "search-results" }, class: "position-relative") do |form| %>
        <div class="form-floating">
          <%= form.text_field :name, placeholder: "Search", class: "form-control", data: { action: "input->search#toggleClearButton"} %>
          <%= form.label :search, for: :name %>
        </div>

        <div class="entry-search-button">
          <%= link_to(root_path, class: "btn btn-sm btn-outline-danger rounded-circle p-0 lh-1 me-2 d-none", data: {search_target: "clearButton"})  do %>
            <i class="bi bi-x"></i>
          <% end %>

          <%= form.button class: "btn btn-primary" do %>
            <i class="bi bi-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= link_to("+ New Entry", new_entry_path, class: "btn btn-primary", data: { turbo_frame: "main-dashboard" }) %>
  </div>

  <div id="dashboard" class="card shadow-sm">
    <div class="entries-card">
      <div class="entries-card__sidebar">
        <%= turbo_frame_tag("search-results") do %>
          <nav id="entries-list" class="nav flex-column">
            <% if @entries.any? %>
              <%= render @entries %>
            <% end %>
          </nav>
        <% end %>
      </div>

      <div class="entries-card__main">
        <%= turbo_frame_tag('main-dashboard') do %>
          <% if @entries.any? %>
            <%= render(partial: "entries/main", locals: { entry: @main_entry }) %>
          <% else %>
            <%= content_tag(:h1, 'No Entries', class: 'h-100 d-flex align-items-center justify-content-center') %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<%= turbo_frame_tag("main-dashboard") do %>
  <div class="d-flex align-items-center justify-content-between">
    <h1>New Entry</h1>
    <%= link_to("Cancel", entries_path, class: "btn btn-sm btn-outline-danger") %>
  </div>

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <% if @entry.errors.any? %>
            <div id="error_explanation" class="alert alert-danger" role="alert">
              <h4>
                Please fix the <%= pluralize(@entry.errors.count, 'error') %>
                below and try again.
              </h4>

              <ul>
                <% @entry.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= form_with(model: @entry) do |form| %>
            <div class="form-floating mb-3">
              <%= form.text_field :name, placeholder: 'Name', class: "form-control" %>
              <%= form.label :name %>
            </div>

            <div class="form-floating mb-3">
              <%= form.text_field :url, placeholder: 'URL', class: "form-control" %>
              <%= form.label :url %>
            </div>

            <div class="form-floating mb-3">
              <%= form.text_field :username, placeholder: 'Username', class: "form-control" %>
              <%= form.label :username %>
            </div>

            <div class="form-floating mb-3">
              <%= form.text_field :password, placeholder: 'Password', class: "form-control" %>
              <%= form.label :password %>
            </div>

            <%= form.submit "Create new entry", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/entries/show.html.erb
<%= turbo_frame_tag('main-dashboard') do %>
  <%= render(partial: "entries/main", locals: { entry: @entry }) %>
<% end %>

app/views/entries/update.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.replace(@entry) %>
<%= turbo_stream.update('main-dashboard') do  %>
  <%= render(partial: 'entries/main', locals: {entry: @entry}) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= content_for(:title) || "Safe Pass App" %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Safe Pass App">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%# = tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render partial: 'shared/navbar' %>
    <div id="flash"><%= render partial: 'shared/flash' %></div>
    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>SafePassApp Secure Authentication</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Safe Pass App">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%# = tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="vh-100">
      <%= render partial: "shared/flash" %>
      <%= render partial: "shared/navbar" if account_page? %>

      <div
        class="
          h-100 container d-flex flex-column justify-content-center
          align-items-center
        "
      >
        <% unless account_page? %>
          <%= logo %>
        <% end %>

        <div class="card card--auth shadow-sm w-100">
          <div class="card-body"><%= yield %></div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<h1>Hello World</h1>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div
    class="
      toast align-items-center text-bg-<%= flash_class(type) %> border-0 position-absolute
      top-0 end-0 z-1 mt-5 me-5
    "
    role="alert"
    aria-live="assertive"
    aria-atomic="true"
    data-controller="toast"
  >
    <div class="d-flex">
      <div class="toast-body"><%= message %></div>

      <button
        type="button"
        class="btn-close btn-close-white me-2 m-auto"
        data-bs-dismiss="toast"
        aria-label="Close"
      ></button>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom mb-5">
  <div class="container">
    <%= logo('h4') %>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Dashboard", root_path, class: "nav-link #{'active' if current_page?(root_path)}" %>
        </li>

        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <i class="bi bi-person-circle"></i>
            </a>

            <ul class="dropdown-menu dropdown-menu-end">
              <li>
                <h6 class="dropdown-header">
                  Signed in as:
                  <br>
                  <%= current_user.email %>
                </h6>
              </li>

              <li><hr class="dropdown-divider"></li>

              <li>
                <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
              </li>

              <li>
                <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link #{'active' if current_page?(root_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>